#!/bin/bash
DIR=`git rev-parse --show-toplevel`
REPONAME=`basename $DIR`
INDEX=$DIR/../.index.$REPONAME.gz
echo Searching $REPONAME
if [ ! -e $INDEX ]
then
echo "No index. Creating $INDEX"
repoindex $DIR
fi

zgrep $@ $INDEX
