#!/bin/bash
DIR=$1
if [ "$DIR" == "" ]
then
	DIR=`git rev-parse --show-toplevel`
fi

REPONAME=`basename $DIR`
INDEX=$DIR/../.index.$REPONAME.gz
echo Indexing $REPONAME to $INDEX

cd $DIR
grep -IR '$' * --exclude-dir=.git --exclude=app.\* --exclude=\*.min.\* --exclude-dir=\*/vendor --exclude-dir=\*/node_modules | gzip -9 > $INDEX


